HEADERS += \
    $$PWD/PickAreaInteractorStyle.h \
    $$PWD/ScriptHandler.h \
    $$PWD/HeuProjectDB.h \
    $$PWD/global.h \
    $$PWD/graphicsanalyse.h \
    $$PWD/graphicsanalyse_global.h \
    $$PWD/smoothfilterpropform.h \
    $$PWD/refelctionfilterpropform.h \
    $$PWD/saveimagedialog.h \
	$$PWD/savescriptdialog.h \
    $$PWD/saveanidialog.h \
    $$PWD/vtkAniThread.h \
    $$PWD/vectorfilterpropform.h \
	$$PWD/streamlinefilterpropform.h \
    $$PWD/slicefilterpropform.h \
    $$PWD/datasourcepropform.h \
    $$PWD/contourfilterpropform.h \
    $$PWD/PipelineObjPlotForm.h \
    $$PWD/PipelineObjPropDockWidget.h \
    $$PWD/PipelineObjTreeDockWidget.h \
    $$PWD/aboutdialog.h \
    $$PWD/consolecmddockwidget.h \
    $$PWD/dropTreeWidget.h \
    $$PWD/FileDialogDirectory.h \
    $$PWD/graph_mainwindow.h \
    $$PWD/pipelineobjpropwidget.h \
	$$PWD/pickcurvedockwidget.h \
	$$PWD/scalarbareditform.h \
	$$PWD/scalarbareditdockwidget.h \
	$$PWD/CTK/Libs/Core/ctkCoreExport.h \
    $$PWD/CTK/Libs/Core/ctkLogger.h \
	$$PWD/CTK/Libs/Core/ctkPimpl.h \
	$$PWD/CTK/Libs/Core/ctkValueProxy.h \
	$$PWD/CTK/Libs/Core/ctkSingleton.h \
    $$PWD/CTK/Libs/Core/ctkUtils.h \
	$$PWD/CTK/Libs/Visualization/VTK/Core/ctkVisualizationVTKCoreExport.h \
    $$PWD/CTK/Libs/Visualization/VTK/Core/ctkVTKConnection.h \
	$$PWD/CTK/Libs/Visualization/VTK/Core/ctkVTKConnection_p.h \
	$$PWD/CTK/Libs/Visualization/VTK/Core/ctkVTKObject.h \
	$$PWD/CTK/Libs/Visualization/VTK/Core/ctkVTKObjectEventsObserver.h \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVisualizationVTKWidgetsExport.h \
    $$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKAbstractMatrixWidget.h \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKAbstractMatrixWidget_p.h \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKChartView.h \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKColorTransferFunction.h \	
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKCompositeFunction.h \
    $$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKHistogram.h \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKLookupTable.h \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKMatrixWidget.h \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKPiecewiseFunction.h \	
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKPropertyWidget.h \
    $$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKScalarBarWidget.h \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKScalarsToColorsUtils.h \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKScalarsToColorsView.h \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKScalarsToColorsWidget.h \	
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKSurfaceMaterialPropertyWidget.h \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKTextPropertyWidget.h \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKThresholdWidget.h \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKVolumePropertyWidget.h \	
	$$PWD/CTK/Libs/Widgets/ctkBasePopupWidget.h \
	$$PWD/CTK/Libs/Widgets/ctkBasePopupWidget_p.h \
	$$PWD/CTK/Libs/Widgets/ctkCollapsibleGroupBox.h \
	$$PWD/CTK/Libs/Widgets/ctkColorDialog.h \
	$$PWD/CTK/Libs/Widgets/ctkColorPickerButton.h \
	$$PWD/CTK/Libs/Widgets/ctkDoubleRangeSlider.h \
	$$PWD/CTK/Libs/Widgets/ctkDoubleSlider.h \
	$$PWD/CTK/Libs/Widgets/ctkDoubleSpinBox.h \
	$$PWD/CTK/Libs/Widgets/ctkDoubleSpinBox_p.h \
	$$PWD/CTK/Libs/Widgets/ctkExpandButton.h \
	$$PWD/CTK/Libs/Widgets/ctkHistogram.h \
	$$PWD/CTK/Libs/Widgets/ctkMaterialPropertyPreviewLabel.h \
	$$PWD/CTK/Libs/Widgets/ctkMaterialPropertyWidget.h \
	$$PWD/CTK/Libs/Widgets/ctkMatrixWidget.h \
    $$PWD/CTK/Libs/Widgets/ctkPopupWidget.h \	
	$$PWD/CTK/Libs/Widgets/ctkPopupWidget_p.h \
	$$PWD/CTK/Libs/Widgets/ctkProxyStyle.h \
	$$PWD/CTK/Libs/Widgets/ctkRangeSlider.h \
	$$PWD/CTK/Libs/Widgets/ctkRangeWidget.h \
	$$PWD/CTK/Libs/Widgets/ctkSliderWidget.h \
	$$PWD/CTK/Libs/Widgets/ctkTransferFunction.h \
	$$PWD/CTK/Libs/Widgets/ctkTransferFunctionBarsItem.h \
	$$PWD/CTK/Libs/Widgets/ctkTransferFunctionControlPointsItem.h \
	$$PWD/CTK/Libs/Widgets/ctkTransferFunctionGradientItem.h \
	$$PWD/CTK/Libs/Widgets/ctkTransferFunctionItem.h \
	$$PWD/CTK/Libs/Widgets/ctkTransferFunctionNativeItem.h \
	$$PWD/CTK/Libs/Widgets/ctkTransferFunctionRepresentation.h \
	$$PWD/CTK/Libs/Widgets/ctkTransferFunctionScene.h \
	$$PWD/CTK/Libs/Widgets/ctkTransferFunctionView.h \
    $$PWD/CTK/Libs/Widgets/ctkWidgetsExport.h \	
    $$PWD/scalarrangedialog.h \
	$$PWD/updateCgnsThread.h \
	$$PWD/rubberZoomInteractorStyle.h \
	$$PWD/actorInteractorStyle.h \
	$$PWD/actorMoveInteractorStyle.h \
	$$PWD/translator.h \
	$$PWD/myInteractorStyle.h \
	$$PWD/LoadActionFile.h \
	$$PWD/loadfiledialog.h \
	$$PWD/exportfiledialog.h \
	$$PWD/exportFileThread.h \
	$$PWD/signalhandlerPy.h \
    $$PWD/calfilterpropform.h \
	$$PWD/disvtkPOVExporter.h

SOURCES += \
    $$PWD/contourfilterpropform.cpp \
    $$PWD/datasourcepropform.cpp \
    $$PWD/FileDialogDirectory.cpp \
    $$PWD/HeuProjectDB.cpp \
    $$PWD/PickAreaInteractorStyle.cpp \
    $$PWD/PipelineObjPlotForm.cpp \
    $$PWD/PipelineObjTreeDockWidget.cpp \
    $$PWD/aboutdialog.cpp \
    $$PWD/consolecmddockwidget.cpp \
    $$PWD/dropTreeWidget.cpp \
    $$PWD/graphicsanalyse.cpp \
    $$PWD/graph_mainwindow.cpp \
    $$PWD/pipelineobjpropdockwidget.cpp \
    $$PWD/pipelineobjpropwidget.cpp \
    $$PWD/refelctionfilterpropform.cpp \
    $$PWD/saveanidialog.cpp \
    $$PWD/saveimagedialog.cpp \
	$$PWD/savescriptdialog.cpp \
    $$PWD/ScriptHandler.cpp \
    $$PWD/slicefilterpropform.cpp \
    $$PWD/smoothfilterpropform.cpp \
    $$PWD/vectorfilterpropform.cpp \
	$$PWD/streamlinefilterpropform.cpp \
    $$PWD/vtkAniThread.cpp \
	$$PWD/global.cpp \
	$$PWD/pickcurvedockwidget.cpp \
	$$PWD/scalarbareditform.cpp \
	$$PWD/scalarbareditdockwidget.cpp \
	$$PWD/CTK/Libs/Core/ctkLogger.cpp \
	$$PWD/CTK/Libs/Core/ctkUtils.cpp \
	$$PWD/CTK/Libs/Core/ctkValueProxy.cpp \	
	$$PWD/CTK/Libs/Visualization/VTK/Core/ctkVTKConnection.cpp \
	$$PWD/CTK/Libs/Visualization/VTK/Core/ctkVTKObjectEventsObserver.cpp \	
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKAbstractMatrixWidget.cpp \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKChartView.cpp \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKColorTransferFunction.cpp \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKCompositeFunction.cpp \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKHistogram.cpp \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKLookupTable.cpp \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKMatrixWidget.cpp \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKPiecewiseFunction.cpp \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKPropertyWidget.cpp \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKScalarBarWidget.cpp \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKScalarsToColorsUtils.cpp \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKScalarsToColorsView.cpp \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKScalarsToColorsWidget.cpp \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKSurfaceMaterialPropertyWidget.cpp \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKTextPropertyWidget.cpp \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKThresholdWidget.cpp \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/ctkVTKVolumePropertyWidget.cpp \	
	$$PWD/CTK/Libs/Widgets/ctkBasePopupWidget.cpp \
	$$PWD/CTK/Libs/Widgets/ctkCollapsibleGroupBox.cpp \
	$$PWD/CTK/Libs/Widgets/ctkColorDialog.cpp \
	$$PWD/CTK/Libs/Widgets/ctkColorPickerButton.cpp \
	$$PWD/CTK/Libs/Widgets/ctkDoubleRangeSlider.cpp \
	$$PWD/CTK/Libs/Widgets/ctkDoubleSlider.cpp \
	$$PWD/CTK/Libs/Widgets/ctkDoubleSpinBox.cpp \
	$$PWD/CTK/Libs/Widgets/ctkExpandButton.cpp \
	$$PWD/CTK/Libs/Widgets/ctkHistogram.cpp \
	$$PWD/CTK/Libs/Widgets/ctkMaterialPropertyPreviewLabel.cpp \
	$$PWD/CTK/Libs/Widgets/ctkMaterialPropertyWidget.cpp \
	$$PWD/CTK/Libs/Widgets/ctkMatrixWidget.cpp \
	$$PWD/CTK/Libs/Widgets/ctkPopupWidget.cpp \
	$$PWD/CTK/Libs/Widgets/ctkProxyStyle.cpp \
	$$PWD/CTK/Libs/Widgets/ctkRangeSlider.cpp \
    $$PWD/CTK/Libs/Widgets/ctkRangeWidget.cpp \	
	$$PWD/CTK/Libs/Widgets/ctkSliderWidget.cpp \
	$$PWD/CTK/Libs/Widgets/ctkTransferFunction.cpp \
	$$PWD/CTK/Libs/Widgets/ctkTransferFunctionBarsItem.cpp \
	$$PWD/CTK/Libs/Widgets/ctkTransferFunctionControlPointsItem.cpp \
	$$PWD/CTK/Libs/Widgets/ctkTransferFunctionGradientItem.cpp \
	$$PWD/CTK/Libs/Widgets/ctkTransferFunctionItem.cpp \
	$$PWD/CTK/Libs/Widgets/ctkTransferFunctionNativeItem.cpp \
	$$PWD/CTK/Libs/Widgets/ctkTransferFunctionRepresentation.cpp \
	$$PWD/CTK/Libs/Widgets/ctkTransferFunctionScene.cpp \
	$$PWD/CTK/Libs/Widgets/ctkTransferFunctionView.cpp \
    $$PWD/scalarrangedialog.cpp \
	$$PWD/updateCgnsThread.cpp \
	$$PWD/rubberZoomInteractorStyle.cpp \
	$$PWD/actorInteractorStyle.cpp \
	$$PWD/actorMoveInteractorStyle.cpp \
	$$PWD/translator.cpp \
	$$PWD/myInteractorStyle.cpp \
	$$PWD/LoadActionFile.cpp \
	$$PWD/loadfiledialog.cpp \
	$$PWD/exportfiledialog.cpp \
	$$PWD/exportFileThread.cpp \
	$$PWD/signalhandlerPy.cpp \
    $$PWD/calfilterpropform.cpp \
	$$PWD/disvtkPOVExporter.cxx
FORMS += \
    $$PWD/PipelineObjPlotForm.ui \
    $$PWD/aboutdialog.ui \
    $$PWD/graph_mainwindow.ui \
    $$PWD/pipelineobjpropwidget.ui \
    $$PWD/FileDialogDirectory.ui \
    $$PWD/datasourcepropform.ui \
    $$PWD/contourfilterpropform.ui \
    $$PWD/slicefilterpropform.ui \
    $$PWD/vectorfilterpropform.ui \
	$$PWD/streamlinefilterpropform.ui \
    $$PWD/saveanidialog.ui \
    $$PWD/refelctionfilterpropform.ui \
    $$PWD/saveimagedialog.ui \
	$$PWD/savescriptdialog.ui \
    $$PWD/smoothfilterpropform.ui \
	$$PWD/scalarbareditform.ui \	
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/Resources/UI/ctkVTKPropertyWidget.ui \
    $$PWD/CTK/Libs/Visualization/VTK/Widgets/Resources/UI/ctkVTKScalarBarWidget.ui \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/Resources/UI/ctkVTKScalarsToColorsWidget.ui \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/Resources/UI/ctkVTKTextPropertyWidget.ui \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/Resources/UI/ctkVTKThresholdWidget.ui \
	$$PWD/CTK/Libs/Visualization/VTK/Widgets/Resources/UI/ctkVTKVolumePropertyWidget.ui \
	$$PWD/CTK/Libs/Widgets/Resources/UI/ctkMaterialPropertyWidget.ui \
	$$PWD/CTK/Libs/Widgets/Resources/UI/ctkRangeWidget.ui \
	$$PWD/CTK/Libs/Widgets/Resources/UI/ctkSliderWidget.ui \
    $$PWD/scalarrangedialog.ui \
	$$PWD/loadfiledialog.ui \
	$$PWD/exportfiledialog.ui \
    $$PWD/calfilterpropform.ui

RESOURCES += resource.qrc
    
	
