rem copy dlls to designer
copy /y ".\DllsForDesigner\selfdeflineeditplugin.dll" "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\plugins\designer"

cd ../
mkdir output
cd output
mkdir bin_d
mkdir bin_d\gmsh
copy /y ".\python37\python37.dll" ".\bin_d"
cd ../

rem copy vtk dlls
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKCOMMONCORE-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKSYS-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKINTERACTIONSTYLE-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKRENDERINGCONTEXTOPENGL2-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKRENDERINGFREETYPE-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKRENDERINGGL2PSOPENGL2-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKRENDERINGOPENGL2-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKRENDERINGVOLUMEOPENGL2-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKRENDERINGCORE-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKCOMMONEXECUTIONMODEL-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKIOGEOMETRY-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKIOLEGACY-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKFILTERSCORE-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKGUISUPPORTQT-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKINTERACTIONWIDGETS-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKRENDERINGANNOTATION-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKCOMMONDATAMODEL-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKFILTERSGENERAL-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKFILTERSMODELING-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKFILTERSSOURCES-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKRENDERINGLOD-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKFILTERSEXTRACTION-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKCOMMONTRANSFORMS-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKCOMMONMATH-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKCOMMONCOLOR-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKFILTERSGEOMETRY-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKCOMMONCOMPUTATIONALGEOMETRY-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKCOMMONMISC-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKRENDERINGCONTEXT2D-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKCOMMONSYSTEM-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKIMAGINGCORE-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKGLEW-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKFREETYPE-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKGL2PS-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKIMAGINGMATH-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKRENDERINGVOLUME-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKFILTERSHYBRID-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKIMAGINGGENERAL-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKIOIMAGE-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKIMAGINGCOLOR-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKFILTERSSTATISTICS-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKDICOMPARSER-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKZLIB-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKPNG-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKMETAIO-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKIMAGINGHYBRID-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKJPEG-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKIOCORE-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKTIFF-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKALGLIB-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKIMAGINGFOURIER-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKIMAGINGSOURCES-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKIOEXPORTOPENGL2-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKIOEXPORT-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKIOIMPORT-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKIOMOVIE-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKOGGTHEORA-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKFILTERSFLOWPATHS-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKCHARTSCORE-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKVIEWSCONTEXT2D-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKINFOVISCORE-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKVIEWSCORE-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKFILTERSVERDICT-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKIOXML-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKVERDICT-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKIOXMLPARSER-7.1.DLL" ".\output\bin_d"
copy /y ".\VTK\vtk_7.1.1_x64_Debug\bin\VTKEXPAT-7.1.DLL" ".\output\bin_d"

rem copy /y "OCC\"
copy /y ".\OCC\opencascade-7.2.0\x64\debug\win64\vc12\bind\TKBRep.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\x64\debug\win64\vc12\bind\TKernel.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\x64\debug\win64\vc12\bind\TKIGES.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\x64\debug\win64\vc12\bind\TKBRep.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\x64\debug\win64\vc12\bind\TKMath.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\x64\debug\win64\vc12\bind\TKSTEP.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\x64\debug\win64\vc12\bind\TKXSBase.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\x64\debug\win64\vc12\bind\TKIVtk.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\x64\debug\win64\vc12\bind\TKV3d.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\x64\debug\win64\vc12\bind\TKGeomBase.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\x64\debug\win64\vc12\bind\TKG3d.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\x64\debug\win64\vc12\bind\TKG2d.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\x64\debug\win64\vc12\bind\TKBool.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\x64\debug\win64\vc12\bind\TKPrim.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\x64\debug\win64\vc12\bind\TKShHealing.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\x64\debug\win64\vc12\bind\TKTopAlgo.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\x64\debug\win64\vc12\bind\TKGeomAlgo.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\x64\debug\win64\vc12\bind\TKSTEPAttr.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\x64\debug\win64\vc12\bind\TKSTEP209.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\x64\debug\win64\vc12\bind\TKSTEPBase.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\x64\debug\win64\vc12\bind\TKMesh.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\x64\debug\win64\vc12\bind\TKService.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\x64\debug\win64\vc12\bind\TKHLR.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\x64\debug\win64\vc12\bind\TKBO.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\x64\debug\win64\vc12\bind\TKOpenGL.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\x64\debug\win64\vc12\bind\TKFILLET.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\x64\debug\win64\vc12\bind\TKOFFSET.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\3rd_party\freeimage-3.17.0-vc12-64\bin\FreeImage.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\3rd_party\freeimage-3.17.0-vc12-64\bin\FreeImagePlus.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\3rd_party\freetype-2.5.5-vc12-64\bin\freetype.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\3rd_party\ffmpeg-3.3-64\bin\avcodec-57.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\3rd_party\ffmpeg-3.3-64\bin\avformat-57.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\3rd_party\ffmpeg-3.3-64\bin\swscale-4.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\3rd_party\ffmpeg-3.3-64\bin\avutil-55.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\3rd_party\ffmpeg-3.3-64\bin\swresample-2.dll" ".\output\bin_d"
copy /y ".\OCC\opencascade-7.2.0\3rd_party\gl2ps-1.3.8-vc12-64\bind\gl2ps.dll" ".\output\bin_d"

rem copy quazip
copy /y ".\quazip\libd\*.lib" ".\output\bin_d"
copy /y ".\quazip\bind\*.dll" ".\output\bin_d"

rem copy Qt dlls
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5Widgetsd.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5Guid.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5Cored.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5Xmld.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5PrintSupportd.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5OpenGLd.dll" ".\output\bin_d"

copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5WebKitWidgetsd.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5Networkd.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5WebKitd.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5Sensorsd.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5MultimediaWidgetsd.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5Multimediad.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5Positioningd.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5WebChanneld.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5PrintSupport.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5Quickd.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5Qmld.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5Sqld.dll" ".\output\bin_d"

copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\icuin53.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\icuuc53.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\icudt53.dll" ".\output\bin_d"
cd .\output\bin_d\
mkdir .\platforms\
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\plugins\platforms\" ".\platforms\" 


rem relaese copy
cd ../
mkdir bin
mkdir bin\gmsh
copy /y ".\python37\python37.dll" ".\bin"
cd ../
rem copy vtk dlls
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKCOMMONCORE-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKSYS-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKINTERACTIONSTYLE-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKRENDERINGCONTEXTOPENGL2-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKRENDERINGFREETYPE-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKRENDERINGGL2PSOPENGL2-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKRENDERINGOPENGL2-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKRENDERINGVOLUMEOPENGL2-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKRENDERINGCORE-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKCOMMONEXECUTIONMODEL-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKIOGEOMETRY-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKIOLEGACY-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKFILTERSCORE-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKGUISUPPORTQT-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKINTERACTIONWIDGETS-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKRENDERINGANNOTATION-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKCOMMONDATAMODEL-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKFILTERSGENERAL-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKFILTERSMODELING-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKFILTERSSOURCES-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKRENDERINGLOD-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKFILTERSEXTRACTION-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKCOMMONTRANSFORMS-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKCOMMONMATH-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKCOMMONCOLOR-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKFILTERSGEOMETRY-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKCOMMONCOMPUTATIONALGEOMETRY-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKCOMMONMISC-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKRENDERINGCONTEXT2D-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKCOMMONSYSTEM-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKIMAGINGCORE-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKGLEW-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKFREETYPE-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKGL2PS-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKIMAGINGMATH-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKRENDERINGVOLUME-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKFILTERSHYBRID-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKIMAGINGGENERAL-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKIOIMAGE-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKIMAGINGCOLOR-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKFILTERSSTATISTICS-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKDICOMPARSER-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKZLIB-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKPNG-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKMETAIO-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKIMAGINGHYBRID-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKJPEG-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKIOCORE-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKTIFF-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKALGLIB-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKIMAGINGFOURIER-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKIMAGINGSOURCES-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKIOEXPORTOPENGL2-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKIOEXPORT-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKIOIMPORT-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKIOMOVIE-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKFILTERSFLOWPATHS-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKCHARTSCORE-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKVIEWSCONTEXT2D-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKINFOVISCORE-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKVIEWSCORE-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKOGGTHEORA-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKFILTERSVERDICT-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKIOXML-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKVERDICT-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKIOXMLPARSER-7.1.DLL" ".\output\bin"
copy /y ".\VTK\vtk_7.1.1_x64_Release\bin\VTKEXPAT-7.1.DLL" ".\output\bin"

rem copy /y "OCC\"
copy /y ".\OCC\opencascade-7.2.0\x64\release\win64\vc12\bin\TKBRep.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\x64\release\win64\vc12\bin\TKernel.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\x64\release\win64\vc12\bin\TKIGES.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\x64\release\win64\vc12\bin\TKBRep.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\x64\release\win64\vc12\bin\TKMath.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\x64\release\win64\vc12\bin\TKSTEP.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\x64\release\win64\vc12\bin\TKXSBase.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\x64\release\win64\vc12\bin\TKIVtk.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\x64\release\win64\vc12\bin\TKV3d.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\x64\release\win64\vc12\bin\TKGeomBase.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\x64\release\win64\vc12\bin\TKG3d.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\x64\release\win64\vc12\bin\TKG2d.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\x64\release\win64\vc12\bin\TKBool.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\x64\release\win64\vc12\bin\TKPrim.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\x64\release\win64\vc12\bin\TKShHealing.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\x64\release\win64\vc12\bin\TKTopAlgo.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\x64\release\win64\vc12\bin\TKGeomAlgo.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\x64\release\win64\vc12\bin\TKSTEPAttr.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\x64\release\win64\vc12\bin\TKSTEP209.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\x64\release\win64\vc12\bin\TKSTEPBase.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\x64\release\win64\vc12\bin\TKMesh.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\x64\release\win64\vc12\bin\TKService.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\x64\release\win64\vc12\bin\TKHLR.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\x64\release\win64\vc12\bin\TKBO.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\x64\release\win64\vc12\bin\TKOpenGl.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\x64\release\win64\vc12\bin\TKFILLET.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\x64\release\win64\vc12\bin\TKOFFSET.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\3rd_party\freeimage-3.17.0-vc12-64\bin\FreeImage.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\3rd_party\freeimage-3.17.0-vc12-64\bin\FreeImagePlus.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\3rd_party\freetype-2.5.5-vc12-64\bin\freetype.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\3rd_party\ffmpeg-3.3-64\bin\avcodec-57.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\3rd_party\ffmpeg-3.3-64\bin\avformat-57.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\3rd_party\ffmpeg-3.3-64\bin\swscale-4.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\3rd_party\ffmpeg-3.3-64\bin\avutil-55.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\3rd_party\ffmpeg-3.3-64\bin\swresample-2.dll" ".\output\bin"
copy /y ".\OCC\opencascade-7.2.0\3rd_party\gl2ps-1.3.8-vc12-64\bin\gl2ps.dll" ".\output\bin"

rem copy quazip
copy /y ".\quazip\lib\*.lib" ".\output\bin"
copy /y ".\quazip\bin\*.dll" ".\output\bin"

rem copy Qt dlls
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5Widgets.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5Gui.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5Core.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5Xml.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5OpenGL.dll" ".\output\bin"

copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5WebKitWidgets.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5Network.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5WebKit.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5Sensors.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5MultimediaWidgets.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5Multimedia.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5Positioning.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5WebChannel.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5PrintSupport.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5Quick.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5Qml.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\Qt5Sql.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\icuin53.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\icuuc53.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\bin\icudt53.dll" ".\output\bin"
cd .\output\bin\
mkdir .\platforms\
copy /y "C:\Qt\Qt5.4.2\5.4\msvc2013_64_opengl\plugins\platforms\" ".\platforms\" 

pause

