#mkdir
mkdir -p ../output/bin
mkdir -p ../output/bin/gmsh

#python
cp -a ../output/python37/lib/libpython3.7m.so.1.0  ../output/bin/

#cgns
cp -a ../cgns/cgns_linux/libcgns.so        ../output/bin/        
#cp -a ../cgns/cgns_linux/libcgns.a        ../output/bin/

#quazip
cp -a ../quazip/lib/libquazip.so   ../output/bin/

#gmsh
cp -a ./Gmsh/gmsh454/gmsh         ../output/bin/gmsh/
cp -a ./Gmsh/gmsh454/gmsh.Geo         ../output/bin/gmsh/
chmod +x ../output/bin/gmsh/gmsh

#QT
cp -a /opt/Qt5.4.2/5.4/gcc_64/lib/libQt5Core.so    ../output/bin/
cp -a /opt/Qt5.4.2/5.4/gcc_64/lib/libQt5Gui.so     ../output/bin/
cp -a /opt/Qt5.4.2/5.4/gcc_64/lib/libQt5OpenGL.so  ../output/bin/
cp -a /opt/Qt5.4.2/5.4/gcc_64/lib/libQt5Widgets.so ../output/bin/
cp -a /opt/Qt5.4.2/5.4/gcc_64/lib/libQt5Xml.so     ../output/bin/
cp -a /opt/Qt5.4.2/5.4/gcc_64/lib/libicudata.so.53 ../output/bin/
cp -a /opt/Qt5.4.2/5.4/gcc_64/lib/libicui18n.so.53 ../output/bin/
cp -a /opt/Qt5.4.2/5.4/gcc_64/lib/libicuio.so.53   ../output/bin/
cp -a /opt/Qt5.4.2/5.4/gcc_64/lib/libicule.so.53   ../output/bin/
cp -a /opt/Qt5.4.2/5.4/gcc_64/lib/libiculx.so.53   ../output/bin/
cp -a /opt/Qt5.4.2/5.4/gcc_64/lib/libicutest.so.53 ../output/bin/
cp -a /opt/Qt5.4.2/5.4/gcc_64/lib/libicutu.so.53   ../output/bin/
cp -a /opt/Qt5.4.2/5.4/gcc_64/lib/libicuuc.so.53   ../output/bin/

cp -a /opt/Qt5.4.2/5.4/gcc_64/lib/libicudata.so.53.1       ../output/bin/
cp -a /opt/Qt5.4.2/5.4/gcc_64/lib/libicui18n.so.53.1       ../output/bin/
cp -a /opt/Qt5.4.2/5.4/gcc_64/lib/libicuio.so.53.1         ../output/bin/
cp -a /opt/Qt5.4.2/5.4/gcc_64/lib/libicule.so.53.1         ../output/bin/
cp -a /opt/Qt5.4.2/5.4/gcc_64/lib/libiculx.so.53.1         ../output/bin/
cp -a /opt/Qt5.4.2/5.4/gcc_64/lib/libicutest.so.53.1       ../output/bin/
cp -a /opt/Qt5.4.2/5.4/gcc_64/lib/libicutu.so.53.1         ../output/bin/
cp -a /opt/Qt5.4.2/5.4/gcc_64/lib/libicuuc.so.53.1         ../output/bin/

cp -a  -R /opt/Qt5.4.2/5.4/gcc_64/plugins/platforms        ../output/bin/

#OCC
cp -a ../OCC/lib/libTKBool.so      ../output/bin/
cp -a ../OCC/lib/libTKBO.so        ../output/bin/
cp -a ../OCC/lib/libTKBRep.so      ../output/bin/
cp -a ../OCC/lib/libTKernel.so     ../output/bin/
cp -a ../OCC/lib/libTKFillet.so    ../output/bin/
cp -a ../OCC/lib/libTKG2d.so       ../output/bin/
cp -a ../OCC/lib/libTKG3d.so       ../output/bin/
cp -a ../OCC/lib/libTKGeomAlgo.so  ../output/bin/
cp -a ../OCC/lib/libTKHLR.so       ../output/bin/
cp -a ../OCC/lib/libTKIGES.so      ../output/bin/
cp -a ../OCC/lib/libTKIVtk.so      ../output/bin/
cp -a ../OCC/lib/libTKMath.so      ../output/bin/
cp -a ../OCC/lib/libTKMesh.so      ../output/bin/
cp -a ../OCC/lib/libTKOffset.so    ../output/bin/
cp -a ../OCC/lib/libTKOpenGl.so    ../output/bin/
cp -a ../OCC/lib/libTKPrim.so      ../output/bin/
cp -a ../OCC/lib/libTKService.so   ../output/bin/
cp -a ../OCC/lib/libTKShHealing.so ../output/bin/
cp -a ../OCC/lib/libTKSTEP209.so   ../output/bin/
cp -a ../OCC/lib/libTKSTEPAttr.so  ../output/bin/
cp -a ../OCC/lib/libTKSTEPBase.so  ../output/bin/
cp -a ../OCC/lib/libTKSTEP.so      ../output/bin/
cp -a ../OCC/lib/libTKTopAlgo.so   ../output/bin/
cp -a ../OCC/lib/libTKV3d.so       ../output/bin/
cp -a ../OCC/lib/libTKXSBase.so    ../output/bin/

cp -a ../OCC/lib/libTKBool.so.7            ../output/bin/
cp -a ../OCC/lib/libTKBO.so.7              ../output/bin/
cp -a ../OCC/lib/libTKBRep.so.7            ../output/bin/
cp -a ../OCC/lib/libTKCDF.so.7             ../output/bin/
cp -a ../OCC/lib/libTKernel.so.7           ../output/bin/
cp -a ../OCC/lib/libTKFillet.so.7          ../output/bin/
cp -a ../OCC/lib/libTKG2d.so.7             ../output/bin/
cp -a ../OCC/lib/libTKG3d.so.7             ../output/bin/
cp -a ../OCC/lib/libTKGeomAlgo.so.7        ../output/bin/
cp -a ../OCC/lib/libTKGeomBase.so.7        ../output/bin/
cp -a ../OCC/lib/libTKHLR.so.7             ../output/bin/
cp -a ../OCC/lib/libTKIGES.so.7            ../output/bin/
cp -a ../OCC/lib/libTKIVtk.so.7            ../output/bin/
cp -a ../OCC/lib/libTKLCAF.so.7            ../output/bin/
cp -a ../OCC/lib/libTKMath.so.7            ../output/bin/
cp -a ../OCC/lib/libTKMesh.so.7            ../output/bin/
cp -a ../OCC/lib/libTKOffset.so.7          ../output/bin/
cp -a ../OCC/lib/libTKOpenGl.so.7          ../output/bin/
cp -a ../OCC/lib/libTKPrim.so.7            ../output/bin/
cp -a ../OCC/lib/libTKService.so.7         ../output/bin/
cp -a ../OCC/lib/libTKShHealing.so.7       ../output/bin/
cp -a ../OCC/lib/libTKSTEP209.so.7         ../output/bin/
cp -a ../OCC/lib/libTKSTEPAttr.so.7        ../output/bin/
cp -a ../OCC/lib/libTKSTEPBase.so.7        ../output/bin/
cp -a ../OCC/lib/libTKSTEP.so.7            ../output/bin/
cp -a ../OCC/lib/libTKTopAlgo.so.7         ../output/bin/
cp -a ../OCC/lib/libTKV3d.so.7             ../output/bin/
cp -a ../OCC/lib/libTKXSBase.so.7          ../output/bin/

cp -a ../OCC/lib/libTKBool.so.7.2.0            ../output/bin/
cp -a ../OCC/lib/libTKBO.so.7.2.0              ../output/bin/
cp -a ../OCC/lib/libTKBRep.so.7.2.0            ../output/bin/
cp -a ../OCC/lib/libTKCDF.so.7.2.0             ../output/bin/
cp -a ../OCC/lib/libTKernel.so.7.2.0           ../output/bin/
cp -a ../OCC/lib/libTKFillet.so.7.2.0          ../output/bin/
cp -a ../OCC/lib/libTKG2d.so.7.2.0             ../output/bin/
cp -a ../OCC/lib/libTKG3d.so.7.2.0             ../output/bin/
cp -a ../OCC/lib/libTKGeomAlgo.so.7.2.0        ../output/bin/
cp -a ../OCC/lib/libTKGeomBase.so.7.2.0        ../output/bin/
cp -a ../OCC/lib/libTKHLR.so.7.2.0             ../output/bin/
cp -a ../OCC/lib/libTKIGES.so.7.2.0            ../output/bin/
cp -a ../OCC/lib/libTKIVtk.so.7.2.0            ../output/bin/
cp -a ../OCC/lib/libTKLCAF.so.7.2.0            ../output/bin/
cp -a ../OCC/lib/libTKMath.so.7.2.0            ../output/bin/
cp -a ../OCC/lib/libTKMesh.so.7.2.0            ../output/bin/
cp -a ../OCC/lib/libTKOffset.so.7.2.0          ../output/bin/
cp -a ../OCC/lib/libTKOpenGl.so.7.2.0          ../output/bin/
cp -a ../OCC/lib/libTKPrim.so.7.2.0            ../output/bin/
cp -a ../OCC/lib/libTKService.so.7.2.0         ../output/bin/
cp -a ../OCC/lib/libTKShHealing.so.7.2.0       ../output/bin/
cp -a ../OCC/lib/libTKSTEP209.so.7.2.0         ../output/bin/
cp -a ../OCC/lib/libTKSTEPAttr.so.7.2.0        ../output/bin/
cp -a ../OCC/lib/libTKSTEPBase.so.7.2.0        ../output/bin/
cp -a ../OCC/lib/libTKSTEP.so.7.2.0            ../output/bin/
cp -a ../OCC/lib/libTKTopAlgo.so.7.2.0         ../output/bin/
cp -a ../OCC/lib/libTKV3d.so.7.2.0             ../output/bin/
cp -a ../OCC/lib/libTKXSBase.so.7.2.0          ../output/bin/


#VTK
cp -a ../VTK/lib/libvtkalglib-7.1.so                       ../output/bin/
cp -a ../VTK/lib/libvtkChartsCore-7.1.so                   ../output/bin/
cp -a ../VTK/lib/libvtkCommonColor-7.1.so                  ../output/bin/
cp -a ../VTK/lib/libvtkCommonComputationalGeometry-7.1.so  ../output/bin/
cp -a ../VTK/lib/libvtkCommonCore-7.1.so                   ../output/bin/
cp -a ../VTK/lib/libvtkCommonDataModel-7.1.so              ../output/bin/
cp -a ../VTK/lib/libvtkCommonExecutionModel-7.1.so         ../output/bin/
cp -a ../VTK/lib/libvtkCommonMath-7.1.so                   ../output/bin/
cp -a ../VTK/lib/libvtkCommonMisc-7.1.so                   ../output/bin/
cp -a ../VTK/lib/libvtkCommonSystem-7.1.so                 ../output/bin/
cp -a ../VTK/lib/libvtkCommonTransforms-7.1.so             ../output/bin/
cp -a ../VTK/lib/libvtkDICOMParser-7.1.so                  ../output/bin/
cp -a ../VTK/lib/libvtkexpat-7.1.so                        ../output/bin/
cp -a ../VTK/lib/libvtkFiltersCore-7.1.so                  ../output/bin/
cp -a ../VTK/lib/libvtkFiltersExtraction-7.1.so            ../output/bin/
cp -a ../VTK/lib/libvtkFiltersFlowPaths-7.1.so             ../output/bin/
cp -a ../VTK/lib/libvtkFiltersGeneral-7.1.so               ../output/bin/
cp -a ../VTK/lib/libvtkFiltersGeometry-7.1.so              ../output/bin/
cp -a ../VTK/lib/libvtkFiltersHybrid-7.1.so                ../output/bin/
cp -a ../VTK/lib/libvtkFiltersModeling-7.1.so              ../output/bin/
cp -a ../VTK/lib/libvtkFiltersSources-7.1.so               ../output/bin/
cp -a ../VTK/lib/libvtkFiltersStatistics-7.1.so            ../output/bin/
cp -a ../VTK/lib/libvtkFiltersVerdict-7.1.so               ../output/bin/
cp -a ../VTK/lib/libvtkfreetype-7.1.so                     ../output/bin/
cp -a ../VTK/lib/libvtkgl2ps-7.1.so                        ../output/bin/
cp -a ../VTK/lib/libvtkglew-7.1.so                         ../output/bin/
cp -a ../VTK/lib/libvtkGUISupportQt-7.1.so                 ../output/bin/
cp -a ../VTK/lib/libvtkImagingColor-7.1.so                 ../output/bin/
cp -a ../VTK/lib/libvtkImagingCore-7.1.so                  ../output/bin/
cp -a ../VTK/lib/libvtkImagingFourier-7.1.so               ../output/bin/
cp -a ../VTK/lib/libvtkImagingGeneral-7.1.so               ../output/bin/
cp -a ../VTK/lib/libvtkImagingHybrid-7.1.so                ../output/bin/
cp -a ../VTK/lib/libvtkImagingMath-7.1.so                  ../output/bin/
cp -a ../VTK/lib/libvtkImagingSources-7.1.so               ../output/bin/
cp -a ../VTK/lib/libvtkInfovisCore-7.1.so                  ../output/bin/
cp -a ../VTK/lib/libvtkInteractionStyle-7.1.so             ../output/bin/
cp -a ../VTK/lib/libvtkInteractionWidgets-7.1.so           ../output/bin/
cp -a ../VTK/lib/libvtkIOCore-7.1.so                       ../output/bin/
cp -a ../VTK/lib/libvtkIOExport-7.1.so                     ../output/bin/
cp -a ../VTK/lib/libvtkIOExportOpenGL2-7.1.so              ../output/bin/
cp -a ../VTK/lib/libvtkIOGeometry-7.1.so                   ../output/bin/
cp -a ../VTK/lib/libvtkIOImage-7.1.so                      ../output/bin/
cp -a ../VTK/lib/libvtkIOImport-7.1.so                     ../output/bin/
cp -a ../VTK/lib/libvtkIOLegacy-7.1.so                     ../output/bin/
cp -a ../VTK/lib/libvtkIOMovie-7.1.so                      ../output/bin/
cp -a ../VTK/lib/libvtkIOXML-7.1.so                        ../output/bin/
cp -a ../VTK/lib/libvtkIOXMLParser-7.1.so                  ../output/bin/
cp -a ../VTK/lib/libvtkjpeg-7.1.so                         ../output/bin/
cp -a ../VTK/lib/libvtkmetaio-7.1.so                       ../output/bin/
cp -a ../VTK/lib/libvtkoggtheora-7.1.so                    ../output/bin/
cp -a ../VTK/lib/libvtkpng-7.1.so                          ../output/bin/
cp -a ../VTK/lib/libvtkRenderingAnnotation-7.1.so          ../output/bin/
cp -a ../VTK/lib/libvtkRenderingContext2D-7.1.so           ../output/bin/
cp -a ../VTK/lib/libvtkRenderingContextOpenGL2-7.1.so      ../output/bin/
cp -a ../VTK/lib/libvtkRenderingCore-7.1.so                ../output/bin/
cp -a ../VTK/lib/libvtkRenderingFreeType-7.1.so            ../output/bin/
cp -a ../VTK/lib/libvtkRenderingGL2PSOpenGL2-7.1.so        ../output/bin/
cp -a ../VTK/lib/libvtkRenderingLOD-7.1.so                 ../output/bin/
cp -a ../VTK/lib/libvtkRenderingOpenGL2-7.1.so             ../output/bin/
cp -a ../VTK/lib/libvtkRenderingVolume-7.1.so              ../output/bin/
cp -a ../VTK/lib/libvtksys-7.1.so                          ../output/bin/
cp -a ../VTK/lib/libvtktiff-7.1.so                         ../output/bin/
cp -a ../VTK/lib/libvtkverdict-7.1.so                      ../output/bin/
cp -a ../VTK/lib/libvtkViewsContext2D-7.1.so               ../output/bin/
cp -a ../VTK/lib/libvtkViewsCore-7.1.so                    ../output/bin/
cp -a ../VTK/lib/libvtkzlib-7.1.so                         ../output/bin/

cp -a ../VTK/lib/libvtkalglib-7.1.so.1                             ../output/bin/
cp -a ../VTK/lib/libvtkChartsCore-7.1.so.1                         ../output/bin/
cp -a ../VTK/lib/libvtkCommonColor-7.1.so.1                        ../output/bin/
cp -a ../VTK/lib/libvtkCommonComputationalGeometry-7.1.so.1        ../output/bin/
cp -a ../VTK/lib/libvtkCommonCore-7.1.so.1                         ../output/bin/
cp -a ../VTK/lib/libvtkCommonDataModel-7.1.so.1                    ../output/bin/
cp -a ../VTK/lib/libvtkCommonExecutionModel-7.1.so.1               ../output/bin/
cp -a ../VTK/lib/libvtkCommonMath-7.1.so.1                         ../output/bin/
cp -a ../VTK/lib/libvtkCommonMisc-7.1.so.1                         ../output/bin/
cp -a ../VTK/lib/libvtkCommonSystem-7.1.so.1                       ../output/bin/
cp -a ../VTK/lib/libvtkCommonTransforms-7.1.so.1                   ../output/bin/
cp -a ../VTK/lib/libvtkDICOMParser-7.1.so.1                        ../output/bin/
cp -a ../VTK/lib/libvtkexpat-7.1.so.1                              ../output/bin/
cp -a ../VTK/lib/libvtkFiltersCore-7.1.so.1                        ../output/bin/
cp -a ../VTK/lib/libvtkFiltersExtraction-7.1.so.1                  ../output/bin/
cp -a ../VTK/lib/libvtkFiltersFlowPaths-7.1.so.1                   ../output/bin/
cp -a ../VTK/lib/libvtkFiltersGeneral-7.1.so.1                     ../output/bin/
cp -a ../VTK/lib/libvtkFiltersGeometry-7.1.so.1                    ../output/bin/
cp -a ../VTK/lib/libvtkFiltersHybrid-7.1.so.1                      ../output/bin/
cp -a ../VTK/lib/libvtkFiltersModeling-7.1.so.1                    ../output/bin/
cp -a ../VTK/lib/libvtkFiltersSources-7.1.so.1                     ../output/bin/
cp -a ../VTK/lib/libvtkFiltersStatistics-7.1.so.1                  ../output/bin/
cp -a ../VTK/lib/libvtkFiltersVerdict-7.1.so.1                     ../output/bin/
cp -a ../VTK/lib/libvtkfreetype-7.1.so.1                           ../output/bin/
cp -a ../VTK/lib/libvtkgl2ps-7.1.so.1                              ../output/bin/
cp -a ../VTK/lib/libvtkglew-7.1.so.1                               ../output/bin/
cp -a ../VTK/lib/libvtkGUISupportQt-7.1.so.1                       ../output/bin/
cp -a ../VTK/lib/libvtkImagingColor-7.1.so.1                       ../output/bin/
cp -a ../VTK/lib/libvtkImagingCore-7.1.so.1                        ../output/bin/
cp -a ../VTK/lib/libvtkImagingFourier-7.1.so.1                     ../output/bin/
cp -a ../VTK/lib/libvtkImagingGeneral-7.1.so.1                     ../output/bin/
cp -a ../VTK/lib/libvtkImagingHybrid-7.1.so.1                      ../output/bin/
cp -a ../VTK/lib/libvtkImagingMath-7.1.so.1                        ../output/bin/
cp -a ../VTK/lib/libvtkImagingSources-7.1.so.1                     ../output/bin/
cp -a ../VTK/lib/libvtkInfovisCore-7.1.so.1                        ../output/bin/
cp -a ../VTK/lib/libvtkInteractionStyle-7.1.so.1                   ../output/bin/
cp -a ../VTK/lib/libvtkInteractionWidgets-7.1.so.1                 ../output/bin/
cp -a ../VTK/lib/libvtkIOCore-7.1.so.1                             ../output/bin/
cp -a ../VTK/lib/libvtkIOExport-7.1.so.1                           ../output/bin/
cp -a ../VTK/lib/libvtkIOExportOpenGL2-7.1.so.1                    ../output/bin/
cp -a ../VTK/lib/libvtkIOGeometry-7.1.so.1                         ../output/bin/
cp -a ../VTK/lib/libvtkIOImage-7.1.so.1                            ../output/bin/
cp -a ../VTK/lib/libvtkIOImport-7.1.so.1                           ../output/bin/
cp -a ../VTK/lib/libvtkIOLegacy-7.1.so.1                           ../output/bin/
cp -a ../VTK/lib/libvtkIOMovie-7.1.so.1                            ../output/bin/
cp -a ../VTK/lib/libvtkIOXML-7.1.so.1                              ../output/bin/
cp -a ../VTK/lib/libvtkIOXMLParser-7.1.so.1                        ../output/bin/
cp -a ../VTK/lib/libvtkjpeg-7.1.so.1                               ../output/bin/
cp -a ../VTK/lib/libvtkmetaio-7.1.so.1                             ../output/bin/
cp -a ../VTK/lib/libvtkoggtheora-7.1.so.1                          ../output/bin/
cp -a ../VTK/lib/libvtkpng-7.1.so.1                                ../output/bin/
cp -a ../VTK/lib/libvtkRenderingAnnotation-7.1.so.1                ../output/bin/        
cp -a ../VTK/lib/libvtkRenderingContext2D-7.1.so.1                 ../output/bin/
cp -a ../VTK/lib/libvtkRenderingContextOpenGL2-7.1.so.1            ../output/bin/
cp -a ../VTK/lib/libvtkRenderingCore-7.1.so.1                      ../output/bin/
cp -a ../VTK/lib/libvtkRenderingFreeType-7.1.so.1                  ../output/bin/
cp -a ../VTK/lib/libvtkRenderingGL2PSOpenGL2-7.1.so.1              ../output/bin/
cp -a ../VTK/lib/libvtkRenderingLOD-7.1.so.1                       ../output/bin/
cp -a ../VTK/lib/libvtkRenderingOpenGL2-7.1.so.1                   ../output/bin/
cp -a ../VTK/lib/libvtkRenderingVolume-7.1.so.1                    ../output/bin/
cp -a ../VTK/lib/libvtkRenderingVolumeOpenGL2-7.1.so.1             ../output/bin/
cp -a ../VTK/lib/libvtksys-7.1.so.1                                ../output/bin/
cp -a ../VTK/lib/libvtktiff-7.1.so.1                               ../output/bin/
cp -a ../VTK/lib/libvtkverdict-7.1.so.1                            ../output/bin/
cp -a ../VTK/lib/libvtkViewsContext2D-7.1.so.1                     ../output/bin/
cp -a ../VTK/lib/libvtkViewsCore-7.1.so.1                          ../output/bin/
cp -a ../VTK/lib/libvtkzlib-7.1.so.1                               ../output/bin/
