set currentPath=%cd%

cd ../
mkdir output
cd output
mkdir bin_d
mkdir bin_d\gmsh
copy /y ".\python37\python37.dll" ".\bin_d"
cd ../

copy /y "%currentPath%\Gmsh\gmsh454\gmsh.exe" ".\output\bin_d\gmsh" 
copy /y "%currentPath%\Gmsh\gmsh454\gmsh.Geo" ".\output\bin_d\gmsh" 

rem copy vtk dlls
copy /y ".\VTK\bind\vtkChartsCore-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkCommonColor-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkCommonComputationalGeometry-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkCommonCore-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkCommonDataModel-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkCommonExecutionModel-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkCommonMath-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkCommonMisc-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkCommonSystem-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkCommonTransforms-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkDICOMParser-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkdoubleconversion-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkexodusII-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkexpat-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkFiltersCore-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkFiltersExtraction-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkFiltersFlowPaths-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkFiltersGeneral-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkFiltersGeometry-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkFiltersHybrid-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkFiltersModeling-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkFiltersSources-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkFiltersStatistics-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkFiltersVerdict-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkfreetype-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkgl2ps-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkglew-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkGUISupportQt-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkhdf5_hl-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkhdf5-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkImagingColor-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkImagingCore-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkImagingFourier-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkImagingGeneral-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkImagingHybrid-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkImagingMath-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkImagingSources-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkInfovisCore-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkInteractionStyle-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkInteractionWidgets-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkIOCore-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkIOExodus-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkIOExport-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkIOExportGL2PS-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkIOGeometry-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkIOImage-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkIOImport-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkIOLegacy-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkIOMovie-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkIOXML-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkIOXMLParser-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkjpeg-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkjsoncpp-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkloguru-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtklz4-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtklzma-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkmetaio-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtknetcdf-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkParallelCore-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkParallelDIY-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkpng-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkpugixml-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkRenderingAnnotation-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkRenderingContext2D-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkRenderingCore-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkRenderingFreeType-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkRenderingGL2PSOpenGL2-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkRenderingOpenGL2-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkRenderingSceneGraph-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkRenderingUI-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkRenderingVolume-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkRenderingVolumeOpenGL2-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkRenderingVtkJS-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtksys-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtktiff-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkverdict-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkViewsContext2D-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkViewsCore-9.0d.dll" ".\output\bin_d"
copy /y ".\VTK\bind\vtkzlib-9.0d.dll" ".\output\bin_d"


rem copy /y "OCC\"
copy /y ".\OCC\win64\vc14\bind\TKernel.dll" ".\output\bin_d"
copy /y ".\OCC\win64\vc14\bind\TKIGES.dll" ".\output\bin_d"
copy /y ".\OCC\win64\vc14\bind\TKBRep.dll" ".\output\bin_d"
copy /y ".\OCC\win64\vc14\bind\TKMath.dll" ".\output\bin_d"
copy /y ".\OCC\win64\vc14\bind\TKSTEP.dll" ".\output\bin_d"
copy /y ".\OCC\win64\vc14\bind\TKXSBase.dll" ".\output\bin_d"
copy /y ".\OCC\win64\vc14\bind\TKIVtk.dll" ".\output\bin_d"
copy /y ".\OCC\win64\vc14\bind\TKV3d.dll" ".\output\bin_d"
copy /y ".\OCC\win64\vc14\bind\TKGeomBase.dll" ".\output\bin_d"
copy /y ".\OCC\win64\vc14\bind\TKG3d.dll" ".\output\bin_d"
copy /y ".\OCC\win64\vc14\bind\TKG2d.dll" ".\output\bin_d"
copy /y ".\OCC\win64\vc14\bind\TKBool.dll" ".\output\bin_d"
copy /y ".\OCC\win64\vc14\bind\TKPrim.dll" ".\output\bin_d"
copy /y ".\OCC\win64\vc14\bind\TKShHealing.dll" ".\output\bin_d"
copy /y ".\OCC\win64\vc14\bind\TKTopAlgo.dll" ".\output\bin_d"
copy /y ".\OCC\win64\vc14\bind\TKGeomAlgo.dll" ".\output\bin_d"
copy /y ".\OCC\win64\vc14\bind\TKSTEPAttr.dll" ".\output\bin_d"
copy /y ".\OCC\win64\vc14\bind\TKSTEP209.dll" ".\output\bin_d"
copy /y ".\OCC\win64\vc14\bind\TKSTEPBase.dll" ".\output\bin_d"
copy /y ".\OCC\win64\vc14\bind\TKMesh.dll" ".\output\bin_d"
copy /y ".\OCC\win64\vc14\bind\TKService.dll" ".\output\bin_d"
copy /y ".\OCC\win64\vc14\bind\TKHLR.dll" ".\output\bin_d"
copy /y ".\OCC\win64\vc14\bind\TKBO.dll" ".\output\bin_d"
copy /y ".\OCC\win64\vc14\bind\TKFillet.dll" ".\output\bin_d"
copy /y ".\OCC\win64\vc14\bind\TKOffset.dll" ".\output\bin_d"
copy /y ".\OCC\win64\vc14\bin\freetype.dll" ".\output\bin_d"

rem copy quazip
copy /y ".\quazip\libd\quazipd.lib" ".\output\bin_d"
copy /y ".\quazip\libd\quazipd.dll" ".\output\bin_d"
copy /y ".\cgns\bind\cgnsdll.dll" ".\output\bin_d"

rem copy Qt dlls
if exist "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5Widgetsd.dll" (
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5Widgetsd.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5Guid.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5Cored.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5Xmld.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5Networkd.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5WebChanneld.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5Quickd.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5Qmld.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5WebEngineCored.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5WebEngineWidgetsd.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5WebViewd.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5QuickWidgetsd.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5QmlModelsd.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5PrintSupportd.dll" ".\output\bin_d"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5Positioningd.dll" ".\output\bin_d"

copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\QtWebEngineProcessd.exe" ".\output\bin_d"

cd .\output\bin_d\
mkdir .\platforms\
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\plugins\platforms\" ".\platforms\" 
mkdir .\resources\
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\resources\" ".\resources\" 
mkdir .\translations\qtwebengine_locales\
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\translations\qtwebengine_locales\" ".\translations\qtwebengine_locales\" 
)

rem relaese copy
cd ../
mkdir bin
mkdir bin\gmsh
copy /y ".\python37\python37.dll" ".\bin"
cd ../

copy /y "%currentPath%\Gmsh\gmsh454\gmsh.exe" ".\output\bin\gmsh" 
copy /y "%currentPath%\Gmsh\gmsh454\gmsh.Geo" ".\output\bin\gmsh" 

rem copy vtk dlls
copy /y ".\VTK\bin\vtkChartsCore-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkCommonColor-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkCommonComputationalGeometry-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkCommonCore-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkCommonDataModel-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkCommonExecutionModel-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkCommonMath-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkCommonMisc-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkCommonSystem-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkCommonTransforms-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkDICOMParser-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkdoubleconversion-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkexodusII-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkexpat-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkFiltersCore-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkFiltersExtraction-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkFiltersFlowPaths-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkFiltersGeneral-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkFiltersGeometry-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkFiltersHybrid-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkFiltersModeling-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkFiltersSources-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkFiltersStatistics-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkFiltersVerdict-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkfreetype-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkgl2ps-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkglew-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkGUISupportQt-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkhdf5_hl-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkhdf5-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkImagingColor-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkImagingCore-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkImagingFourier-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkImagingGeneral-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkImagingHybrid-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkImagingMath-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkImagingSources-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkInfovisCore-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkInteractionStyle-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkInteractionWidgets-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkIOCore-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkIOExodus-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkIOExport-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkIOExportGL2PS-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkIOGeometry-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkIOImage-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkIOImport-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkIOLegacy-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkIOMovie-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkIOXML-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkIOXMLParser-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkjpeg-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkjsoncpp-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkloguru-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtklz4-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtklzma-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkmetaio-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtknetcdf-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkParallelCore-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkParallelDIY-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkpng-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkpugixml-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkRenderingAnnotation-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkRenderingContext2D-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkRenderingCore-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkRenderingFreeType-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkRenderingGL2PSOpenGL2-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkRenderingOpenGL2-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkRenderingSceneGraph-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkRenderingUI-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkRenderingVolume-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkRenderingVolumeOpenGL2-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkRenderingVtkJS-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtksys-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtktiff-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkverdict-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkViewsContext2D-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkViewsCore-9.0.dll" ".\output\bin"
copy /y ".\VTK\bin\vtkzlib-9.0.dll" ".\output\bin"

rem copy /y "OCC\"
copy /y ".\OCC\win64\vc14\bin\TKernel.dll" ".\output\bin"
copy /y ".\OCC\win64\vc14\bin\TKIGES.dll" ".\output\bin"
copy /y ".\OCC\win64\vc14\bin\TKBRep.dll" ".\output\bin"
copy /y ".\OCC\win64\vc14\bin\TKMath.dll" ".\output\bin"
copy /y ".\OCC\win64\vc14\bin\TKSTEP.dll" ".\output\bin"
copy /y ".\OCC\win64\vc14\bin\TKXSBase.dll" ".\output\bin"
copy /y ".\OCC\win64\vc14\bin\TKIVtk.dll" ".\output\bin"
copy /y ".\OCC\win64\vc14\bin\TKV3d.dll" ".\output\bin"
copy /y ".\OCC\win64\vc14\bin\TKGeomBase.dll" ".\output\bin"
copy /y ".\OCC\win64\vc14\bin\TKG3d.dll" ".\output\bin"
copy /y ".\OCC\win64\vc14\bin\TKG2d.dll" ".\output\bin"
copy /y ".\OCC\win64\vc14\bin\TKBool.dll" ".\output\bin"
copy /y ".\OCC\win64\vc14\bin\TKPrim.dll" ".\output\bin"
copy /y ".\OCC\win64\vc14\bin\TKShHealing.dll" ".\output\bin"
copy /y ".\OCC\win64\vc14\bin\TKTopAlgo.dll" ".\output\bin"
copy /y ".\OCC\win64\vc14\bin\TKGeomAlgo.dll" ".\output\bin"
copy /y ".\OCC\win64\vc14\bin\TKSTEPAttr.dll" ".\output\bin"
copy /y ".\OCC\win64\vc14\bin\TKSTEP209.dll" ".\output\bin"
copy /y ".\OCC\win64\vc14\bin\TKSTEPBase.dll" ".\output\bin"
copy /y ".\OCC\win64\vc14\bin\TKMesh.dll" ".\output\bin"
copy /y ".\OCC\win64\vc14\bin\TKService.dll" ".\output\bin"
copy /y ".\OCC\win64\vc14\bin\TKHLR.dll" ".\output\bin"
copy /y ".\OCC\win64\vc14\bin\TKBO.dll" ".\output\bin"
copy /y ".\OCC\win64\vc14\bin\TKFillet.dll" ".\output\bin"
copy /y ".\OCC\win64\vc14\bin\TKOffset.dll" ".\output\bin"
copy /y ".\OCC\win64\vc14\bin\freetype.dll" ".\output\bin"

rem copy quazip
copy /y ".\quazip\lib\quazip.lib" ".\output\bin"
copy /y ".\quazip\lib\quazip.dll" ".\output\bin"
copy /y ".\cgns\bin\cgnsdll.dll" ".\output\bin"

rem copy Qt dlls
if exist "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5Widgets.dll" (
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5Widgets.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5Gui.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5Core.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5Xml.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5Network.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5WebChannel.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5Quick.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5Qml.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5WebEngineCore.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5WebEngineWidgets.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5WebView.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5QuickWidgets.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5QmlModels.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5PrintSupport.dll" ".\output\bin"
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\Qt5Positioning.dll" ".\output\bin"

copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin\QtWebEngineProcess.exe" ".\output\bin"

cd .\output\bin\
mkdir .\platforms\
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\plugins\platforms\" ".\platforms\" 
mkdir .\resources\
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\resources\" ".\resources\" 
mkdir .\translations\qtwebengine_locales\
copy /y "C:\Qt\Qt5.14.2\5.14.2\msvc2017_64\translations\qtwebengine_locales\" ".\translations\qtwebengine_locales\" 
)
pause

