#pragma once
#include <vtkAutoInit.h>
VTK_MODULE_INIT(vtkRenderingOpenGL2);
VTK_MODULE_INIT(vtkInteractionStyle);

#include <vtkSmartPointer.h>
#include <vtkRenderer.h>
#include <vtkRenderWindow.h>
#include <vtkRenderWindowInteractor.h>
#include <vtkInteractorStyleTrackballCamera.h>
#include <vtkPolyDataMapper.h>
#include <vtkActor.h>
#include <vtkLight.h>
#include <vtkCamera.h>
//#include <QVTKWidget.h>
#include <vtkPoints.h>
#include <vtkCellArray.h>
#include <vtkCellData.h>
#include <vtkVertex.h>
#include <vtkPolyData.h>
#include <vtkPolyDataMapper.h>
#include <vtkProperty.h>
#include <vtkPolygon.h>
#include <vtkFloatArray.h>
#include <vtkLookupTable.h>
#include <vtkTetra.h>
#include <vtkLine.h>
#include <vtkLineSource.h>
#include <vtkInteractorStyleTrackballActor.h>
#include <vtkPropPicker.h>
#include <vtkPolyDataSilhouette.h>
#include <vtkPolyDataWriter.h>
#include <vtkPolyLine.h>
#include <vtkCellPicker.h>
#include <vtkRendererCollection.h>
#include <vtkUnstructuredGrid.h>
#include <vtkDataSetMapper.h>
#include <vtkXMLUnstructuredGridWriter.h>
#include <vtkUnstructuredGridWriter.h>
#include <vtkPointData.h>
#include <vtkDoubleArray.h>
#include <vtkPolyVertex.h>
#include <vtkDataSetReader.h>
#include <vtkDataSetWriter.h>
#include <vtkAppendPolyData.h>