#ifndef _PARACLASSFACTORY_H_
#define _PARACLASSFACTORY_H_

#include <QtCore/QtGlobal>


#if defined(PARACLASSFACTORY_API)
#define PARACLASSFACTORYAPI Q_DECL_EXPORT
#else
#define PARACLASSFACTORYAPI Q_DECL_IMPORT
#endif

#endif
