#ifndef HEUDATASRCIO_GLOBAL_H
#define HEUDATASRCIO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HEUDATASRCIO_LIBRARY)
#  define HEUDATASRCIOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HEUDATASRCIOSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HEUDATASRCIO_GLOBAL_H
