/* DO NOT EDIT.
 * Generated by ..\..\bin\Debug\vtkEncodeString-7.1.exe
 * 
 * Declare the raycastervs string.
 *
 */
#ifndef __raycastervs_h
#define __raycastervs_h

#include "vtkRenderingVolumeOpenGL2Module.h"

VTKRENDERINGVOLUMEOPENGL2_EXPORT extern const char *raycastervs;

#endif /* #ifndef __raycastervs_h */
