/* DO NOT EDIT.
 * Generated by ..\..\bin\Debug\vtkEncodeString-7.1.exe
 * 
 * Declare the vtkDepthPeelingPassFinalFS string.
 *
 */
#ifndef __vtkDepthPeelingPassFinalFS_h
#define __vtkDepthPeelingPassFinalFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkDepthPeelingPassFinalFS;

#endif /* #ifndef __vtkDepthPeelingPassFinalFS_h */
