/* DO NOT EDIT.
 * Generated by ..\..\bin\Debug\vtkEncodeString-7.1.exe
 * 
 * Declare the vtkEDLBilateralFilterFS string.
 *
 */
#ifndef __vtkEDLBilateralFilterFS_h
#define __vtkEDLBilateralFilterFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkEDLBilateralFilterFS;

#endif /* #ifndef __vtkEDLBilateralFilterFS_h */
