/* DO NOT EDIT.
 * Generated by ..\..\bin\Debug\vtkEncodeString-7.1.exe
 * 
 * Declare the vtkEDLShadeFS string.
 *
 */
#ifndef __vtkEDLShadeFS_h
#define __vtkEDLShadeFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkEDLShadeFS;

#endif /* #ifndef __vtkEDLShadeFS_h */
