/* DO NOT EDIT.
 * Generated by ..\..\bin\Debug\vtkEncodeString-7.1.exe
 * 
 * Declare the vtkglProjectedTetrahedraVS string.
 *
 */
#ifndef __vtkglProjectedTetrahedraVS_h
#define __vtkglProjectedTetrahedraVS_h

#include "vtkRenderingVolumeOpenGL2Module.h"

VTKRENDERINGVOLUMEOPENGL2_EXPORT extern const char *vtkglProjectedTetrahedraVS;

#endif /* #ifndef __vtkglProjectedTetrahedraVS_h */
