/* DO NOT EDIT.
 * Generated by ..\..\bin\Debug\vtkEncodeString-7.1.exe
 * 
 * Declare the vtkLineIntegralConvolution2D_AAV string.
 *
 */
#ifndef __vtkLineIntegralConvolution2D_AAV_h
#define __vtkLineIntegralConvolution2D_AAV_h

#include "vtkRenderingLICOpenGL2Module.h"

VTKRENDERINGLICOPENGL2_EXPORT extern const char *vtkLineIntegralConvolution2D_AAV;

#endif /* #ifndef __vtkLineIntegralConvolution2D_AAV_h */
