/* DO NOT EDIT.
 * Generated by ..\..\bin\Debug\vtkEncodeString-7.1.exe
 * 
 * Declare the vtkPolyDataVS string.
 *
 */
#ifndef __vtkPolyDataVS_h
#define __vtkPolyDataVS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkPolyDataVS;

#endif /* #ifndef __vtkPolyDataVS_h */
