/* DO NOT EDIT.
 * Generated by ..\..\bin\Debug\vtkEncodeString-7.1.exe
 * 
 * Declare the vtkPolyDataWideLineGS string.
 *
 */
#ifndef __vtkPolyDataWideLineGS_h
#define __vtkPolyDataWideLineGS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkPolyDataWideLineGS;

#endif /* #ifndef __vtkPolyDataWideLineGS_h */
