/* DO NOT EDIT.
 * Generated by ..\..\bin\Debug\vtkEncodeString-7.1.exe
 * 
 * Declare the vtkPointFillPassFS string.
 *
 */
#ifndef __vtkPointFillPassFS_h
#define __vtkPointFillPassFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkPointFillPassFS;

#endif /* #ifndef __vtkPointFillPassFS_h */
