/* DO NOT EDIT.
 * Generated by ..\..\bin\Debug\vtkEncodeString-7.1.exe
 * 
 * Declare the vtkSurfaceLICInterface_CE string.
 *
 */
#ifndef __vtkSurfaceLICInterface_CE_h
#define __vtkSurfaceLICInterface_CE_h

#include "vtkRenderingLICOpenGL2Module.h"

VTKRENDERINGLICOPENGL2_EXPORT extern const char *vtkSurfaceLICInterface_CE;

#endif /* #ifndef __vtkSurfaceLICInterface_CE_h */
