/* DO NOT EDIT.
 * Generated by ..\..\bin\Debug\vtkEncodeString-7.1.exe
 * 
 * Declare the vtkSurfaceLICInterface_DCpy string.
 *
 */
#ifndef __vtkSurfaceLICInterface_DCpy_h
#define __vtkSurfaceLICInterface_DCpy_h

#include "vtkRenderingLICOpenGL2Module.h"

VTKRENDERINGLICOPENGL2_EXPORT extern const char *vtkSurfaceLICInterface_DCpy;

#endif /* #ifndef __vtkSurfaceLICInterface_DCpy_h */
