set(AutobahnPython_LOADED 1)
set(AutobahnPython_DEPENDS "SixPython;Twisted;vtkPython")
set(AutobahnPython_LIBRARIES "D:/python 2.6x64/libs/python26.lib")
set(AutobahnPython_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(AutobahnPython_LIBRARY_DIRS "")
set(AutobahnPython_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(AutobahnPython_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/AutobahnPythonHierarchy.txt")
set(AutobahnPython_KIT "")
set(AutobahnPython_EXCLUDE_FROM_WRAPPING 1)

