set(Twisted_LOADED 1)
set(Twisted_DEPENDS "ZopeInterface;vtkPython")
set(Twisted_LIBRARIES "D:/python 2.6x64/libs/python26.lib")
set(Twisted_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(Twisted_LIBRARY_DIRS "")
set(Twisted_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(Twisted_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/TwistedHierarchy.txt")
set(Twisted_KIT "")
set(Twisted_EXCLUDE_FROM_WRAPPING 1)

