set(vtkalglib_LOADED 1)
set(vtkalglib_DEPENDS "")
set(vtkalglib_LIBRARIES "vtkalglib")
set(vtkalglib_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtkalglib_LIBRARY_DIRS "")
set(vtkalglib_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkalglib_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkalglibHierarchy.txt")
set(vtkalglib_KIT "")
set(vtkalglib_EXCLUDE_FROM_WRAPPING 1)

