set(vtkDomainsChemistryOpenGL2_LOADED 1)
set(vtkDomainsChemistryOpenGL2_DEPENDS "vtkCommonCore;vtkCommonDataModel;vtkCommonExecutionModel;vtkCommonMath;vtkDomainsChemistry;vtkDomainsChemistry;vtkRenderingCore;vtkRenderingOpenGL2;vtkglew")
set(vtkDomainsChemistryOpenGL2_LIBRARIES "vtkDomainsChemistryOpenGL2")
set(vtkDomainsChemistryOpenGL2_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtkDomainsChemistryOpenGL2_LIBRARY_DIRS "")
set(vtkDomainsChemistryOpenGL2_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkDomainsChemistryOpenGL2_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkDomainsChemistryOpenGL2Hierarchy.txt")
set(vtkDomainsChemistryOpenGL2_KIT "vtkOpenGL")
set(vtkDomainsChemistryOpenGL2_IMPLEMENTS "vtkDomainsChemistry")

