set(vtkfreetype_LOADED 1)
set(vtkfreetype_DEPENDS "vtkkwiml;vtkzlib")
set(vtkfreetype_LIBRARIES "vtkfreetype")
set(vtkfreetype_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtkfreetype_LIBRARY_DIRS "")
set(vtkfreetype_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkfreetype_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkfreetypeHierarchy.txt")
set(vtkfreetype_KIT "")
set(vtkfreetype_EXCLUDE_FROM_WRAPPING 1)

