set(vtkGUISupportMFC_LOADED 1)
set(vtkGUISupportMFC_DEPENDS "vtkRenderingOpenGL2")
set(vtkGUISupportMFC_LIBRARIES "vtkGUISupportMFC")
set(vtkGUISupportMFC_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtkGUISupportMFC_LIBRARY_DIRS "")
set(vtkGUISupportMFC_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkGUISupportMFC_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkGUISupportMFCHierarchy.txt")
set(vtkGUISupportMFC_KIT "")
set(vtkGUISupportMFC_EXCLUDE_FROM_WRAPPING 1)

