set(vtkglew_LOADED 1)
set(vtkglew_DEPENDS "")
set(vtkglew_LIBRARIES "vtkglew")
set(vtkglew_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtkglew_LIBRARY_DIRS "")
set(vtkglew_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkglew_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkglewHierarchy.txt")
set(vtkglew_KIT "")
set(vtkglew_EXCLUDE_FROM_WRAPPING 1)

