set(vtklibproj4_LOADED 1)
set(vtklibproj4_DEPENDS "")
set(vtklibproj4_LIBRARIES "vtkproj4")
set(vtklibproj4_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtklibproj4_LIBRARY_DIRS "")
set(vtklibproj4_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtklibproj4_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtklibproj4Hierarchy.txt")
set(vtklibproj4_KIT "")
set(vtklibproj4_EXCLUDE_FROM_WRAPPING 1)

