set(vtkPython_LOADED 1)
set(vtkPython_DEPENDS "vtkCommonCore")
set(vtkPython_LIBRARIES "D:/python 2.6x64/libs/python26.lib")
set(vtkPython_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1;D:/python 2.6x64/include")
set(vtkPython_LIBRARY_DIRS "")
set(vtkPython_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkPython_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkPythonHierarchy.txt")
set(vtkPython_KIT "")
set(vtkPython_EXCLUDE_FROM_WRAPPING 1)

