set(vtkRenderingVolumeOpenGL2_LOADED 1)
set(vtkRenderingVolumeOpenGL2_DEPENDS "vtkCommonCore;vtkCommonDataModel;vtkCommonMath;vtkCommonSystem;vtkCommonTransforms;vtkFiltersCore;vtkFiltersGeneral;vtkFiltersSources;vtkImagingCore;vtkImagingMath;vtkRenderingCore;vtkRenderingOpenGL2;vtkRenderingVolume;vtkRenderingVolume;vtkglew;vtksys")
set(vtkRenderingVolumeOpenGL2_LIBRARIES "vtkRenderingVolumeOpenGL2")
set(vtkRenderingVolumeOpenGL2_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtkRenderingVolumeOpenGL2_LIBRARY_DIRS "")
set(vtkRenderingVolumeOpenGL2_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkRenderingVolumeOpenGL2_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkRenderingVolumeOpenGL2Hierarchy.txt")
set(vtkRenderingVolumeOpenGL2_KIT "vtkOpenGL")
set(vtkRenderingVolumeOpenGL2_IMPLEMENTS "vtkRenderingVolume")

