set(vtkRenderingGL2PSOpenGL2_LOADED 1)
set(vtkRenderingGL2PSOpenGL2_DEPENDS "vtkCommonCore;vtkCommonDataModel;vtkCommonMath;vtkRenderingCore;vtkRenderingOpenGL2;vtkRenderingOpenGL2;vtkRenderingOpenGL2;vtkgl2ps")
set(vtkRenderingGL2PSOpenGL2_LIBRARIES "vtkRenderingGL2PSOpenGL2")
set(vtkRenderingGL2PSOpenGL2_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtkRenderingGL2PSOpenGL2_LIBRARY_DIRS "")
set(vtkRenderingGL2PSOpenGL2_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkRenderingGL2PSOpenGL2_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkRenderingGL2PSOpenGL2Hierarchy.txt")
set(vtkRenderingGL2PSOpenGL2_KIT "")
set(vtkRenderingGL2PSOpenGL2_IMPLEMENTS "vtkRenderingOpenGL2")

