set(vtkUtilitiesEncodeString_LOADED 1)
set(vtkUtilitiesEncodeString_DEPENDS "")
set(vtkUtilitiesEncodeString_LIBRARIES "")
set(vtkUtilitiesEncodeString_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtkUtilitiesEncodeString_LIBRARY_DIRS "")
set(vtkUtilitiesEncodeString_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkUtilitiesEncodeString_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkUtilitiesEncodeStringHierarchy.txt")
set(vtkUtilitiesEncodeString_KIT "")
set(vtkUtilitiesEncodeString_EXCLUDE_FROM_WRAPPING 1)

