set(vtkverdict_LOADED 1)
set(vtkverdict_DEPENDS "")
set(vtkverdict_LIBRARIES "verdict")
set(vtkverdict_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtkverdict_LIBRARY_DIRS "")
set(vtkverdict_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkverdict_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkverdictHierarchy.txt")
set(vtkverdict_KIT "")
set(vtkverdict_EXCLUDE_FROM_WRAPPING 1)

