set(vtkzlib_LOADED 1)
set(vtkzlib_DEPENDS "")
set(vtkzlib_LIBRARIES "vtkzlib")
set(vtkzlib_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtkzlib_LIBRARY_DIRS "")
set(vtkzlib_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkzlib_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkzlibHierarchy.txt")
set(vtkzlib_KIT "")
set(vtkzlib_EXCLUDE_FROM_WRAPPING 1)

