
#ifndef VTKCOMMONCOMPUTATIONALGEOMETRY_EXPORT_H
#define VTKCOMMONCOMPUTATIONALGEOMETRY_EXPORT_H

#ifdef VTKCOMMONCOMPUTATIONALGEOMETRY_STATIC_DEFINE
#  define VTKCOMMONCOMPUTATIONALGEOMETRY_EXPORT
#  define VTKCOMMONCOMPUTATIONALGEOMETRY_NO_EXPORT
#else
#  ifndef VTKCOMMONCOMPUTATIONALGEOMETRY_EXPORT
#    ifdef CommonComputationalGeometry_EXPORTS
        /* We are building this library */
#      define VTKCOMMONCOMPUTATIONALGEOMETRY_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define VTKCOMMONCOMPUTATIONALGEOMETRY_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef VTKCOMMONCOMPUTATIONALGEOMETRY_NO_EXPORT
#    define VTKCOMMONCOMPUTATIONALGEOMETRY_NO_EXPORT 
#  endif
#endif

#ifndef VTKCOMMONCOMPUTATIONALGEOMETRY_DEPRECATED
#  define VTKCOMMONCOMPUTATIONALGEOMETRY_DEPRECATED __declspec(deprecated)
#endif

#ifndef VTKCOMMONCOMPUTATIONALGEOMETRY_DEPRECATED_EXPORT
#  define VTKCOMMONCOMPUTATIONALGEOMETRY_DEPRECATED_EXPORT VTKCOMMONCOMPUTATIONALGEOMETRY_EXPORT VTKCOMMONCOMPUTATIONALGEOMETRY_DEPRECATED
#endif

#ifndef VTKCOMMONCOMPUTATIONALGEOMETRY_DEPRECATED_NO_EXPORT
#  define VTKCOMMONCOMPUTATIONALGEOMETRY_DEPRECATED_NO_EXPORT VTKCOMMONCOMPUTATIONALGEOMETRY_NO_EXPORT VTKCOMMONCOMPUTATIONALGEOMETRY_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef VTKCOMMONCOMPUTATIONALGEOMETRY_NO_DEPRECATED
#    define VTKCOMMONCOMPUTATIONALGEOMETRY_NO_DEPRECATED
#  endif
#endif

#endif /* VTKCOMMONCOMPUTATIONALGEOMETRY_EXPORT_H */
