#ifndef ACTIONTYPE_H
#define ACTIONTYPE_H

enum TASK_STATE {
    TASK_STATE_NON,
    TASK_STATE_LGN, /// login
    TASK_STATE_LGNFAILED,
    TASK_STATE_LGNCOMPLETE,
    TASK_STATE_CREATE,
    TASK_STATE_CREATED,
    TASK_STATE_CREATEDFAILED,
    TASK_STATE_CREATECOMPLETE,
    TASK_STATE_DEL,
    TASK_STATE_DELFAILED,
    TASK_STATE_DELCOMPLETE,
    TASK_STATE_UCOMMIT,
    TASK_STATE_UCOMMITEDFAILED,
    TASK_STATE_UCOMMITEDCOMPLETE,
    TASK_STATE_CALC,
    TASK_STATE_CALCING,
    TASK_STATE_CALCFAILED,
    TASK_STATE_CALCOMPLETE,
    TASK_STATE_DRESULT,
    TASK_STATE_DRESULTFAILED,
    TASK_STATE_DRESULTCOMPLETE,
    TASK_STATE_SEL,
    TASK_STATE_SELFAILED,
    TASK_STATE_SELCOMPLETE,
    TASK_STATE_STOP,
    TASK_STATE_STOPFAILED,
    TASK_STATE_STOPCOMPLETE,
    TASK_STATE_PREPARE,
    TASK_STATE_PENDING,
    TASK_STATE_CANCEL,
    TASK_STATE_FAIL,
    TASK_STATE_SUSPENDED,
    TASK_STATE_RUN,
    TASK_STATE_UNKNOWN,
    TASK_STATE_CANCELLING
};

#endif // ACTIONTYPE_H
