/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-7.1.exe
 * 
 * Declare the vtkDepthPeelingPassIntermediateFS string.
 *
 */
#ifndef __vtkDepthPeelingPassIntermediateFS_h
#define __vtkDepthPeelingPassIntermediateFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkDepthPeelingPassIntermediateFS;

#endif /* #ifndef __vtkDepthPeelingPassIntermediateFS_h */
