/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-7.1.exe
 * 
 * Declare the vtkFXAAFilterFS string.
 *
 */
#ifndef __vtkFXAAFilterFS_h
#define __vtkFXAAFilterFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkFXAAFilterFS;

#endif /* #ifndef __vtkFXAAFilterFS_h */
