/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-7.1.exe
 * 
 * Declare the vtkglProjectedTetrahedraFS string.
 *
 */
#ifndef __vtkglProjectedTetrahedraFS_h
#define __vtkglProjectedTetrahedraFS_h

#include "vtkRenderingVolumeOpenGL2Module.h"

VTKRENDERINGVOLUMEOPENGL2_EXPORT extern const char *vtkglProjectedTetrahedraFS;

#endif /* #ifndef __vtkglProjectedTetrahedraFS_h */
