/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-7.1.exe
 * 
 * Declare the vtkGaussianBlurPassFS string.
 *
 */
#ifndef __vtkGaussianBlurPassFS_h
#define __vtkGaussianBlurPassFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkGaussianBlurPassFS;

#endif /* #ifndef __vtkGaussianBlurPassFS_h */
