/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-7.1.exe
 * 
 * Declare the vtkGaussianBlurPassVS string.
 *
 */
#ifndef __vtkGaussianBlurPassVS_h
#define __vtkGaussianBlurPassVS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkGaussianBlurPassVS;

#endif /* #ifndef __vtkGaussianBlurPassVS_h */
