/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-7.1.exe
 * 
 * Declare the vtkLineIntegralConvolution2D_AAH string.
 *
 */
#ifndef __vtkLineIntegralConvolution2D_AAH_h
#define __vtkLineIntegralConvolution2D_AAH_h

#include "vtkRenderingLICOpenGL2Module.h"

VTKRENDERINGLICOPENGL2_EXPORT extern const char *vtkLineIntegralConvolution2D_AAH;

#endif /* #ifndef __vtkLineIntegralConvolution2D_AAH_h */
