/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-7.1.exe
 * 
 * Declare the vtkPolyData2DFS string.
 *
 */
#ifndef __vtkPolyData2DFS_h
#define __vtkPolyData2DFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkPolyData2DFS;

#endif /* #ifndef __vtkPolyData2DFS_h */
