/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-7.1.exe
 * 
 * Declare the vtkPolyDataFS string.
 *
 */
#ifndef __vtkPolyDataFS_h
#define __vtkPolyDataFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkPolyDataFS;

#endif /* #ifndef __vtkPolyDataFS_h */
