/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-7.1.exe
 * 
 * Declare the vtkPolyData2DVS string.
 *
 */
#ifndef __vtkPolyData2DVS_h
#define __vtkPolyData2DVS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkPolyData2DVS;

#endif /* #ifndef __vtkPolyData2DVS_h */
