/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-7.1.exe
 * 
 * Declare the vtkPointGaussianVS string.
 *
 */
#ifndef __vtkPointGaussianVS_h
#define __vtkPointGaussianVS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkPointGaussianVS;

#endif /* #ifndef __vtkPointGaussianVS_h */
