/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-7.1.exe
 * 
 * Declare the vtkSSAAPassFS string.
 *
 */
#ifndef __vtkSSAAPassFS_h
#define __vtkSSAAPassFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkSSAAPassFS;

#endif /* #ifndef __vtkSSAAPassFS_h */
