/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-7.1.exe
 * 
 * Declare the vtkSphereMapperVS string.
 *
 */
#ifndef __vtkSphereMapperVS_h
#define __vtkSphereMapperVS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkSphereMapperVS;

#endif /* #ifndef __vtkSphereMapperVS_h */
