/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-7.1.exe
 * 
 * Declare the vtkStructuredGridLIC2D_fs string.
 *
 */
#ifndef __vtkStructuredGridLIC2D_fs_h
#define __vtkStructuredGridLIC2D_fs_h

#include "vtkRenderingLICOpenGL2Module.h"

VTKRENDERINGLICOPENGL2_EXPORT extern const char *vtkStructuredGridLIC2D_fs;

#endif /* #ifndef __vtkStructuredGridLIC2D_fs_h */
