/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-7.1.exe
 * 
 * Declare the vtkSurfaceLICInterface_SC string.
 *
 */
#ifndef __vtkSurfaceLICInterface_SC_h
#define __vtkSurfaceLICInterface_SC_h

#include "vtkRenderingLICOpenGL2Module.h"

VTKRENDERINGLICOPENGL2_EXPORT extern const char *vtkSurfaceLICInterface_SC;

#endif /* #ifndef __vtkSurfaceLICInterface_SC_h */
