/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-7.1.exe
 * 
 * Declare the vtkTextureObjectFS string.
 *
 */
#ifndef __vtkTextureObjectFS_h
#define __vtkTextureObjectFS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkTextureObjectFS;

#endif /* #ifndef __vtkTextureObjectFS_h */
