/* DO NOT EDIT.
 * Generated by ..\..\bin\Release\vtkEncodeString-7.1.exe
 * 
 * Declare the vtkTextureObjectVS string.
 *
 */
#ifndef __vtkTextureObjectVS_h
#define __vtkTextureObjectVS_h

#include "vtkRenderingOpenGL2Module.h"

VTKRENDERINGOPENGL2_EXPORT extern const char *vtkTextureObjectVS;

#endif /* #ifndef __vtkTextureObjectVS_h */
