
#ifndef VTKTESTINGGENERICBRIDGE_EXPORT_H
#define VTKTESTINGGENERICBRIDGE_EXPORT_H

#ifdef VTKTESTINGGENERICBRIDGE_STATIC_DEFINE
#  define VTKTESTINGGENERICBRIDGE_EXPORT
#  define VTKTESTINGGENERICBRIDGE_NO_EXPORT
#else
#  ifndef VTKTESTINGGENERICBRIDGE_EXPORT
#    ifdef vtkTestingGenericBridge_EXPORTS
        /* We are building this library */
#      define VTKTESTINGGENERICBRIDGE_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define VTKTESTINGGENERICBRIDGE_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef VTKTESTINGGENERICBRIDGE_NO_EXPORT
#    define VTKTESTINGGENERICBRIDGE_NO_EXPORT 
#  endif
#endif

#ifndef VTKTESTINGGENERICBRIDGE_DEPRECATED
#  define VTKTESTINGGENERICBRIDGE_DEPRECATED __declspec(deprecated)
#  define VTKTESTINGGENERICBRIDGE_DEPRECATED_EXPORT VTKTESTINGGENERICBRIDGE_EXPORT __declspec(deprecated)
#  define VTKTESTINGGENERICBRIDGE_DEPRECATED_NO_EXPORT VTKTESTINGGENERICBRIDGE_NO_EXPORT __declspec(deprecated)
#endif

#define DEFINE_NO_DEPRECATED 0
#if DEFINE_NO_DEPRECATED
# define VTKTESTINGGENERICBRIDGE_NO_DEPRECATED
#endif



#endif
