set(SixPython_LOADED 1)
set(SixPython_DEPENDS "vtkPython")
set(SixPython_LIBRARIES "D:/Python 2.7x64/libs/python27.lib")
set(SixPython_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(SixPython_LIBRARY_DIRS "")
set(SixPython_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(SixPython_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/SixPythonHierarchy.txt")
set(SixPython_KIT "")
set(SixPython_EXCLUDE_FROM_WRAPPING 1)

