set(vtkCommonCore_LOADED 1)
set(vtkCommonCore_DEPENDS "vtkkwiml;vtksys")
set(vtkCommonCore_LIBRARIES "vtkCommonCore")
set(vtkCommonCore_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtkCommonCore_LIBRARY_DIRS "")
set(vtkCommonCore_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkCommonCore_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkCommonCoreHierarchy.txt")
set(vtkCommonCore_KIT "vtkCommon")
set(VTK_DEBUG_LEAKS "OFF")
set(VTK_USE_64BIT_IDS "ON")
set(VTK_ALL_NEW_OBJECT_FACTORY "OFF")

