set(vtkDICOMParser_LOADED 1)
set(vtkDICOMParser_DEPENDS "vtksys")
set(vtkDICOMParser_LIBRARIES "vtkDICOMParser")
set(vtkDICOMParser_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtkDICOMParser_LIBRARY_DIRS "")
set(vtkDICOMParser_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkDICOMParser_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkDICOMParserHierarchy.txt")
set(vtkDICOMParser_KIT "")
set(vtkDICOMParser_EXCLUDE_FROM_WRAPPING 1)

