set(vtkexpat_LOADED 1)
set(vtkexpat_DEPENDS "")
set(vtkexpat_LIBRARIES "vtkexpat")
set(vtkexpat_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtkexpat_LIBRARY_DIRS "")
set(vtkexpat_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkexpat_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkexpatHierarchy.txt")
set(vtkexpat_KIT "")
set(vtkexpat_EXCLUDE_FROM_WRAPPING 1)

