set(vtkInteractionStyle_LOADED 1)
set(vtkInteractionStyle_DEPENDS "vtkCommonCore;vtkCommonDataModel;vtkCommonMath;vtkCommonTransforms;vtkFiltersExtraction;vtkFiltersSources;vtkRenderingCore;vtkRenderingCore")
set(vtkInteractionStyle_LIBRARIES "vtkInteractionStyle")
set(vtkInteractionStyle_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtkInteractionStyle_LIBRARY_DIRS "")
set(vtkInteractionStyle_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkInteractionStyle_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkInteractionStyleHierarchy.txt")
set(vtkInteractionStyle_KIT "vtkInteraction")
set(vtkInteractionStyle_IMPLEMENTS "vtkRenderingCore")

