set(vtkIOExportOpenGL2_LOADED 1)
set(vtkIOExportOpenGL2_DEPENDS "vtkCommonCore;vtkCommonDataModel;vtkIOExport;vtkIOExport;vtkImagingCore;vtkRenderingCore;vtkRenderingGL2PSOpenGL2;vtkgl2ps")
set(vtkIOExportOpenGL2_LIBRARIES "vtkIOExportOpenGL2")
set(vtkIOExportOpenGL2_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtkIOExportOpenGL2_LIBRARY_DIRS "")
set(vtkIOExportOpenGL2_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkIOExportOpenGL2_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkIOExportOpenGL2Hierarchy.txt")
set(vtkIOExportOpenGL2_KIT "")
set(vtkIOExportOpenGL2_IMPLEMENTS "vtkIOExport")

