set(vtkjpeg_LOADED 1)
set(vtkjpeg_DEPENDS "")
set(vtkjpeg_LIBRARIES "vtkjpeg")
set(vtkjpeg_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtkjpeg_LIBRARY_DIRS "")
set(vtkjpeg_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkjpeg_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkjpegHierarchy.txt")
set(vtkjpeg_KIT "")
set(vtkjpeg_EXCLUDE_FROM_WRAPPING 1)

