set(vtkjsoncpp_LOADED 1)
set(vtkjsoncpp_DEPENDS "")
set(vtkjsoncpp_LIBRARIES "vtkjsoncpp")
set(vtkjsoncpp_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtkjsoncpp_LIBRARY_DIRS "")
set(vtkjsoncpp_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkjsoncpp_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkjsoncppHierarchy.txt")
set(vtkjsoncpp_KIT "")
set(vtkjsoncpp_EXCLUDE_FROM_WRAPPING 1)

