set(vtkkwiml_LOADED 1)
set(vtkkwiml_DEPENDS "")
set(vtkkwiml_LIBRARIES "")
set(vtkkwiml_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtkkwiml_LIBRARY_DIRS "")
set(vtkkwiml_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkkwiml_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkkwimlHierarchy.txt")
set(vtkkwiml_KIT "")
set(vtkkwiml_EXCLUDE_FROM_WRAPPING 1)

