set(vtklibxml2_LOADED 1)
set(vtklibxml2_DEPENDS "vtkzlib")
set(vtklibxml2_LIBRARIES "vtklibxml2")
set(vtklibxml2_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtklibxml2_LIBRARY_DIRS "")
set(vtklibxml2_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtklibxml2_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtklibxml2Hierarchy.txt")
set(vtklibxml2_KIT "")
set(vtklibxml2_EXCLUDE_FROM_WRAPPING 1)

