set(vtkoggtheora_LOADED 1)
set(vtkoggtheora_DEPENDS "")
set(vtkoggtheora_LIBRARIES "vtkoggtheora")
set(vtkoggtheora_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtkoggtheora_LIBRARY_DIRS "")
set(vtkoggtheora_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkoggtheora_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkoggtheoraHierarchy.txt")
set(vtkoggtheora_KIT "")
set(vtkoggtheora_EXCLUDE_FROM_WRAPPING 1)

