set(vtkpng_LOADED 1)
set(vtkpng_DEPENDS "vtkzlib")
set(vtkpng_LIBRARIES "vtkpng")
set(vtkpng_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtkpng_LIBRARY_DIRS "")
set(vtkpng_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkpng_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkpngHierarchy.txt")
set(vtkpng_KIT "")
set(vtkpng_EXCLUDE_FROM_WRAPPING 1)

