set(vtkRenderingOpenVR_LOADED 1)
set(vtkRenderingOpenVR_DEPENDS "vtkCommonCore;vtkInteractionStyle;vtkRenderingOpenGL2;vtkRenderingOpenGL2;vtkglew")
set(vtkRenderingOpenVR_LIBRARIES "vtkRenderingOpenVR")
set(vtkRenderingOpenVR_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1;D:/XMG/Library/VTK/vtk7.1.1/VTK-7.1.1/3rd_party/openvr-1.0.2/headers;D:/XMG/Library/VTK/vtk7.1.1/VTK-7.1.1/3rd_party/SDL2-2.0.7/include")
set(vtkRenderingOpenVR_LIBRARY_DIRS "")
set(vtkRenderingOpenVR_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkRenderingOpenVR_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkRenderingOpenVRHierarchy.txt")
set(vtkRenderingOpenVR_KIT "")
set(vtkRenderingOpenVR_IMPLEMENTS "vtkRenderingOpenGL2")

