set(vtkRenderingContextOpenGL2_LOADED 1)
set(vtkRenderingContextOpenGL2_DEPENDS "vtkCommonCore;vtkCommonDataModel;vtkCommonMath;vtkCommonTransforms;vtkImagingCore;vtkRenderingContext2D;vtkRenderingContext2D;vtkRenderingCore;vtkRenderingFreeType;vtkRenderingOpenGL2;vtkglew")
set(vtkRenderingContextOpenGL2_LIBRARIES "vtkRenderingContextOpenGL2")
set(vtkRenderingContextOpenGL2_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtkRenderingContextOpenGL2_LIBRARY_DIRS "")
set(vtkRenderingContextOpenGL2_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkRenderingContextOpenGL2_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkRenderingContextOpenGL2Hierarchy.txt")
set(vtkRenderingContextOpenGL2_KIT "vtkOpenGL")
set(vtkRenderingContextOpenGL2_IMPLEMENTS "vtkRenderingContext2D")

