set(vtkRenderingFreeType_LOADED 1)
set(vtkRenderingFreeType_DEPENDS "vtkCommonCore;vtkCommonDataModel;vtkCommonExecutionModel;vtkFiltersGeneral;vtkRenderingCore;vtkRenderingCore;vtkfreetype")
set(vtkRenderingFreeType_LIBRARIES "vtkRenderingFreeType")
set(vtkRenderingFreeType_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtkRenderingFreeType_LIBRARY_DIRS "")
set(vtkRenderingFreeType_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkRenderingFreeType_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkRenderingFreeTypeHierarchy.txt")
set(vtkRenderingFreeType_KIT "vtkRendering")
set(vtkRenderingFreeType_IMPLEMENTS "vtkRenderingCore")

