set(vtksqlite_LOADED 1)
set(vtksqlite_DEPENDS "")
set(vtksqlite_LIBRARIES "vtksqlite")
set(vtksqlite_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtksqlite_LIBRARY_DIRS "")
set(vtksqlite_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtksqlite_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtksqliteHierarchy.txt")
set(vtksqlite_KIT "")
set(vtksqlite_EXCLUDE_FROM_WRAPPING 1)

