set(vtksys_LOADED 1)
set(vtksys_DEPENDS "")
set(vtksys_LIBRARIES "vtksys")
set(vtksys_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtksys_LIBRARY_DIRS "")
set(vtksys_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtksys_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtksysHierarchy.txt")
set(vtksys_KIT "")
set(vtksys_EXCLUDE_FROM_WRAPPING 1)

