set(vtkTestingGenericBridge_LOADED 1)
set(vtkTestingGenericBridge_DEPENDS "vtkCommonCore;vtkCommonDataModel;vtkCommonMisc")
set(vtkTestingGenericBridge_LIBRARIES "vtkTestingGenericBridge")
set(vtkTestingGenericBridge_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtkTestingGenericBridge_LIBRARY_DIRS "")
set(vtkTestingGenericBridge_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkTestingGenericBridge_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkTestingGenericBridgeHierarchy.txt")
set(vtkTestingGenericBridge_KIT "")
set(vtkTestingGenericBridge_EXCLUDE_FROM_WRAPPING 1)

