set(vtkTestingCore_LOADED 1)
set(vtkTestingCore_DEPENDS "vtkCommonCore")
set(vtkTestingCore_LIBRARIES "vtkCommonCore")
set(vtkTestingCore_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtkTestingCore_LIBRARY_DIRS "")
set(vtkTestingCore_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkTestingCore_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkTestingCoreHierarchy.txt")
set(vtkTestingCore_KIT "")
set(vtkTestingCore_EXCLUDE_FROM_WRAPPING 1)

