set(vtkTestingIOSQL_LOADED 1)
set(vtkTestingIOSQL_DEPENDS "vtkIOSQL")
set(vtkTestingIOSQL_LIBRARIES "vtkTestingIOSQL")
set(vtkTestingIOSQL_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtkTestingIOSQL_LIBRARY_DIRS "")
set(vtkTestingIOSQL_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkTestingIOSQL_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkTestingIOSQLHierarchy.txt")
set(vtkTestingIOSQL_KIT "")
set(vtkTestingIOSQL_EXCLUDE_FROM_WRAPPING 1)

