set(vtkWebPython_LOADED 1)
set(vtkWebPython_DEPENDS "AutobahnPython;vtkPython")
set(vtkWebPython_LIBRARIES "D:/Python 2.7x64/libs/python27.lib")
set(vtkWebPython_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtkWebPython_LIBRARY_DIRS "")
set(vtkWebPython_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkWebPython_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkWebPythonHierarchy.txt")
set(vtkWebPython_KIT "")
set(vtkWebPython_EXCLUDE_FROM_WRAPPING 1)

