set(vtkWrappingTools_LOADED 1)
set(vtkWrappingTools_DEPENDS "vtkCommonCore;vtksys")
set(vtkWrappingTools_LIBRARIES "vtkWrappingTools")
set(vtkWrappingTools_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(vtkWrappingTools_LIBRARY_DIRS "")
set(vtkWrappingTools_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(vtkWrappingTools_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/vtkWrappingToolsHierarchy.txt")
set(vtkWrappingTools_KIT "")
set(vtkWrappingTools_EXCLUDE_FROM_WRAPPING 1)

