set(ZopeInterface_LOADED 1)
set(ZopeInterface_DEPENDS "vtkPython")
set(ZopeInterface_LIBRARIES "D:/Python 2.7x64/libs/python27.lib")
set(ZopeInterface_INCLUDE_DIRS "${VTK_INSTALL_PREFIX}/include/vtk-7.1")
set(ZopeInterface_LIBRARY_DIRS "")
set(ZopeInterface_RUNTIME_LIBRARY_DIRS "${VTK_INSTALL_PREFIX}/bin")
set(ZopeInterface_WRAP_HIERARCHY_FILE "${CMAKE_CURRENT_LIST_DIR}/ZopeInterfaceHierarchy.txt")
set(ZopeInterface_KIT "")
set(ZopeInterface_EXCLUDE_FROM_WRAPPING 1)

